sonar.projectKey=PenFlow
sonar.projectName=PenFlow

sonar.sources=backend/app,frontend,workers/app
sonar.tests=backend/tests,workers/tests

sonar.python.coverage.reportPaths=backend/coverage.xml,workers/coverage.xml

sonar.cpd.exclusions=**/docker/postgres/init/**,**/*.sql

sonar.exclusions=\
**/.next/**,\
**/node_modules/**,\
**/__pycache__/**,\
**/*.pyc,\
**/docker/postgres/init/**,\
**/*.sql
