FROM python:3.12-slim AS deps

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY workers/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade pip \ 
&& pip install --no-cache-dir -r requirements.txt

FROM python:3.12-slim AS runner

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY --from=deps /usr/local /usr/local
COPY workers/app ./app

RUN adduser --disabled-password --gecos "" appuser && \
    chown -R appuser:appuser /app

USER appuser

CMD ["celery", "-A", "app.queue.celery_app:celery_app", "worker", "--loglevel=info"]