[mypy]
python_version = 3.12
strict = True
[mypy-celery.*,Wappalyzer.*,whois.*,weasyprint.*]
ignore_missing_imports = True
[mypy-app.*]
disallow_untyped_decorators = False
disallow_any_generics = False
disable_error_code = arg-type, return-value, no-any-return, call-overload, attr-defined, comparison-overlap, dict-item, var-annotated, type-arg